ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount_ht  NUMERIC(10,2) DEFAULT 0;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount_ttc NUMERIC(10,2) DEFAULT 0;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS taux_tva   NUMERIC(5,2)  DEFAULT 20;
SELECT 'expenses HT/TTC ajoutés ✅' AS status;
